version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: trading_journal
      MYSQL_USER: trader
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  api:
    build: ./backend
    depends_on:
      - db
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: trader
      DB_PASSWORD: changeme
      DB_NAME: trading_journal
      JWT_SECRET: supersecretkey
      JWT_REFRESH_SECRET: anothersecret
    ports:
      - '5000:5000'

  client:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - '5173:5173'
    depends_on:
      - api

volumes:
  db_data:
